on:
  push:
    branches:
    - gh_pages
    - main
  schedule:
    - cron: "1 9,11,19 * * *"

name: Dashboard Update

jobs:
  Dashboard-Update:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RENV_PATHS_ROOT: ~/.local/share/renv
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'
          use-public-rspm: true

      - name: Install curl
        run: sudo apt -y install libcurl4-openssl-dev

      - name: Cache packages
        uses: actions/cache@v2
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Install R textshaping deps
        run: sudo apt-get install libharfbuzz-dev libfribidi-dev

      - name: Restore packages
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()
        shell: Rscript {0}

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install workflow dependencies
        run: |
          install.packages(c("rcmdcheck", "sessioninfo", "devtools"))
        shell: Rscript {0}

      - name: Set locale
        run: |
          sudo apt-get update && sudo apt-get install tzdata locales -y && sudo locale-gen pt_BR.UTF-8
          sudo localectl set-locale LANG="pt_BR.UTF-8"
          export LANG="pt_BR.UTF-8"
          sudo update-locale
          locale -a
          locale
          locale -c -k LC_NUMERIC
          localectl status

      - name: ETL
        run: |
          devtools::load_all()
          withr::local_locale(c("LC_TIME" = "pt_BR.utf8"))
          etl_econ_activity()
          etl_fiscal()
          etl_inflation()
          etl_labor()
          etl_monetary()
        shell: Rscript {0}

      - name: Render R Markdown
        run: |
          devtools::load_all()
          withr::local_locale(c("LC_TIME" = "en_US.UTF-8"))
          retry(rmarkdown::render(input = "index.Rmd", output_file = "index", output_dir = "docs"))
          labor_path <- "inst/extdata/labor.Rdata"
          if (file.info(labor_path)[, "size"] > 90000000) {file.remove(labor_path)}
        shell: Rscript {0}

      - name: Commit results
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add .
          git commit -m "Update model and dashboard" || echo "No changes to commit"
          git push origin || echo "No changes to commit"

      - name: Session info
        run: |
          options(width = 500)
          pkgs <- installed.packages()[, "Package"]
          sessioninfo::session_info(pkgs, include_base = TRUE)
        shell: Rscript {0}
